src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @ORM\OneToMany(targetEntity="MovieSee", mappedBy="movie_id")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $Rated;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Released;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $director;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $writer;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $actors;

    /**
     * @ORM\Column(type="text")
     */
    private $plot;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $languages;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $awards;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poster;

    /**
     * @ORM\Column(type="array")
     */
    private $rating = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $metascore;

    /**
     * @ORM\Column(type="float")
     */
    private $imdbrating;

    /**
     * @ORM\Column(type="float")
     */
    private $imdbVotes;

    /**
     * @ORM\Column(type="string", length=255)
     * @ORM\OneToMany(targetEntity="MovieSee", mappedBy="imdbID")
     */
    private $imdbID;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $DVD;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $boxoffice;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $production;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $runtime;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getRated(): ?string
    {
        return $this->Rated;
    }

    public function setRated(string $Rated): self
    {
        $this->Rated = $Rated;

        return $this;
    }

    public function getReleased(): ?string
    {
        return $this->Released;
    }

    public function setReleased(?string $Released): self
    {
        $this->Released = $Released;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getWriter(): ?string
    {
        return $this->writer;
    }

    public function setWriter(?string $writer): self
    {
        $this->writer = $writer;

        return $this;
    }

    public function getActors(): ?string
    {
        return $this->actors;
    }

    public function setActors(string $actors): self
    {
        $this->actors = $actors;

        return $this;
    }

    public function getPlot(): ?string
    {
        return $this->plot;
    }

    public function setPlot(?string $plot): self
    {
        $this->plot = $plot;

        return $this;
    }

    public function getLanguages(): ?string
    {
        return $this->languages;
    }

    public function setLanguages(string $languages): self
    {
        $this->languages = $languages;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAwards(): ?string
    {
        return $this->awards;
    }

    public function setAwards(string $awards): self
    {
        $this->awards = $awards;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getRating(): ?array
    {
        return $this->rating;
    }

    public function setRating(array $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getMetascore(): ?int
    {
        return $this->metascore;
    }

    public function setMetascore(int $metascore): self
    {
        $this->metascore = $metascore;

        return $this;
    }

    public function getImdbrating(): ?float
    {
        return $this->imdbrating;
    }

    public function setImdbrating(float $imdbrating): self
    {
        $this->imdbrating = $imdbrating;

        return $this;
    }

    public function getImdbVotes(): ?float
    {
        return $this->imdbVotes;
    }

    public function setImdbVotes(float $imdbVotes): self
    {
        $this->imdbVotes = $imdbVotes;

        return $this;
    }

    public function getImdbID(): ?string
    {
        return $this->imdbID;
    }

    public function setImdbID(string $imdbID): self
    {
        $this->imdbID = $imdbID;

        return $this;
    }

    public function getDVD(): string
    {
        return $this->DVD;
    }

    public function setDVD(string $DVD): self
    {
        $this->DVD = $DVD;

        return $this;
    }

    public function getBoxoffice(): ?string
    {
        return $this->boxoffice;
    }

    public function setBoxoffice(string $boxoffice): self
    {
        $this->boxoffice = $boxoffice;

        return $this;
    }

    public function getProduction(): ?string
    {
        return $this->production;
    }

    public function setProduction(string $production): self
    {
        $this->production = $production;

        return $this;
    }

    public function getRuntime(): ?string
    {
        return $this->runtime;
    }

    public function setRuntime(string $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }
}

src/Entity/MovieToSee.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieToSeeRepository")
 */
class MovieToSee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=54)
     * @ORM\OneToOne(targetEntity="App\Entity\Movie", mappedBy="imdbID")
     * @ORM\OneToOne(targetEntity="App\Entity\MovieSee", mappedBy="imdbID")
     */
    private $imdbID;

    /**
     * @ORM\Column(type="boolean")
     */
    private $to_see;

    /**
     * @ORM\Column(type="integer")
     * @ORM\OneToOne(targetEntity="App\Entity\Movie", mappedBy="id")
     * @ORM\OneToOne(targetEntity="App\Entity\MovieSee", mappedBy="movie_id")
     */
    private $movie_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImdbID(): ?string
    {
        return $this->imdbID;
    }

    public function setImdbID(string $imdbID): self
    {
        $this->imdbID = $imdbID;

        return $this;
    }

    public function getTooSee(): ?bool
    {
        return $this->to_see;
    }

    public function setTooSee(bool $to_see): self
    {
        $this->to_see = $to_see;

        return $this;
    }

    public function getMovieId(): ?int
    {
        return $this->movie_id;
    }

    public function setMovieId(int $movie_id): self
    {
        $this->movie_id = $movie_id;

        return $this;
    }

    public function getToSee(): ?bool
    {
        return $this->to_see;
    }

    public function setToSee(bool $to_see): self
    {
        $this->to_see = $to_see;

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Twig\Environment;

use App\Entity\Movie;
use App\Entity\MovieSee;
use App\Entity\MovieToSee;

use App\Controller\ManageOmdbApi;
use App\Controller\MovieWatchingController;


class MovieController extends AbstractController
{
    private $twig;
    private $omdb;
    private $watching;

    public function __construct(
        Environment $twig, 
        ManageOmdbApi $omdb,
        MovieWatchingController $watching
    ) {
        $this->twig = $twig;
        $this->omdb = $omdb;
        $this->watching = $watching;
    }

    public function listMovies()
    {
        $movies = $this->getDoctrine()
            ->getRepository(Movie::class)
            ->findAll();

        return $this->render('movie/index.html.twig', ['movies' => $movies]);
    }

    public function getSearchPage($messages = []) 
    {
        $response = $this->twig->render('movie/search.html.twig', [
            'search' => '',
            'messages' => $messages
        ]);

        return new Response($response);
    }

    public function useSearchPagePost(Request $request) {
        $search = $request->get('search');
        $page = $request->get('page');

        return $this->forward('App\Controller\MovieController::useSearchPage', [
            'search' => $search,
            'page' => $page,
        ]);
    }

    public function useSearchPage($page = 1, $search = '') {
        $search = $search;
        $page = $page;

        $results = $this->omdb->searchMovie($search, $page);

        if ($results['Response'] == 'False') {
            return $this->render('movie/search.html.twig',[
                'error' => $results['Error'],
                'search' => $search
            ]);
        } else {
            $results = $results['Search'];

            $watch_infos = $this->watching->getWatchInfoArray($results);

            $response = $this->twig->render('movie/search.html.twig',[
                'results' => $results,
                'search' => $search,
                'page' => $page,
                'watch_infos' => $watch_infos
            ]);

            return new Response($response);
        }
    }
}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des films</h1>

    <table>
        <thead>
            <tr>
                <th>Titre</th>
                <th>Année</th>
                <th>Acteurs</th>
            </tr>
        </thead>
        {% for movie in movies %}
            <tr>
                <td>{{ movie.name }}</td>
                <td>{{ movie.year }}</td>
                <td>{{ movie.actors }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/movie/listMovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieSeeController!{% endblock %}

{% block body %}
    <div class='search'>
        <div class="wrapper">        
            {% if messages is defined and messages|length > 0 %}
                <div class='messages'>
                    {% for imdbID, message in messages %}
                        <p>{{ imdbID }} {{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <h1>{{ title }}</h1>

            <form method="post" action='{{ path("searchMovie") }}'>
                <input type="hidden" name='page' value='1'>
            
              
            </form>
        

            {% if movies is defined %}
                <form method="post" name="action" action="{{ path('updateTooSeeAndSeeMovieInfo') }}"> 
                    <table>
                        <thead>
                            <th>Poster</th>
                            <th>Titre</th>
                            <th>Film à voir</th>
                            <th>Film vu</th>
                        </thead>
                        <tbody>
                            {% for key, movie in movies %}
                                {% if watch_infos.toSee[movie.imdbID] is not null %}
                                    {% set to_see = 'checked' %}
                                {% else %}
                                    {% set to_see = '' %}
                                {% endif %}

                                {% if watch_infos.see[movie.imdbID] is not null %}
                                    {% set see = 'checked' %}
                                {% else %}
                                    {% set see = '' %}
                                {% endif %}

                                <tr>
                                    <td>
                                        <input 
                                            type="hidden" 
                                            name="movies[{{ movie.imdbID }}][imdbID]" 
                                            value="{{ movie.imdbID }}"
                                        >

                                        <a href="{{ path('getMovieDetail', {'imdbID': movie.imdbID}) }}">
                                            <img src="{{ movie.poster }}" alt="poster" class='poster'>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('getMovieDetail', {'imdbID': movie.imdbID}) }}">
                                            {{ movie.name }} <br> {{ movie.year }} 
                                        </a>
                                    </td>
                                    <td>
                                        <label class="container">
                                            <input 
                                                type="checkbox" 
                                                name='movies[{{ movie.imdbID }}][to_see]'
                                                {{ to_see }}
                                            >
                                            <span class="checkmark"></span>
                                        </label>
                                    </td>
                                    <td>
                                        <label class="container">
                                            <input 
                                                type="checkbox" 
                                                name='movies[{{ movie.imdbID }}][see]' 
                                                {{ see }}
                                            >
                                            <span class="checkmark"></span>
                                        </label>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class='bottom-form'>
                        <input type="submit" value="Enregister" class="rkmd-btn btn-green ripple-effect">   
                    </div>
                </form>
            {% endif %}

        {% if error is defined and error|length > 0 %}
            <div class='error'>
                <span>
                    {{ error }}
                </span>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/movie/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chercher un film{% endblock %}

{% block body %}
    <div class='search'>
        <div class="wrapper">        
            {% if messages is defined and messages|length > 0 %}
                <div class='messages'>
                    {% for imdbID, message in messages %}
                        <p>{{ imdbID }} {{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <h1>Chercher un film</h1>

            <form method="post" action='{{ path("searchMovie") }}' class="form-search">
                <input type="hidden" name='page' value='1'>
                
                <div class="group">
                    <input type="text" name="search" value={{ search }}>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Titre</label>
                </div>
                
                <input type="submit" value="Chercher" class='rkmd-btn btn-orange ripple-effect'/>
            </form>
        

            {% if results is defined %}
                <form method="post" name="action" action="{{ path('updateTooSeeAndSeeMovieInfo') }}"> 
                    <table>
                        <thead>
                            <th>Poster</th>
                            <th>Titre</th>
                            <th>Film/Série</th>
                            <th>Film à voir</th>
                            <th>Film vu</th>
                        </thead>
                        <tbody>
                            {% for key, result in results %}
                                {% if watch_infos.toSee[result.imdbID] is not null %}
                                    {% set to_see = 'checked' %}
                                {% else %}
                                    {% set to_see = '' %}
                                {% endif %}

                                {% if watch_infos.see[result.imdbID] is not null %}
                                    {% set see = 'checked' %}
                                {% else %}
                                    {% set see = '' %}
                                {% endif %}

                                <tr>
                                    <td>
                                        <a href="{{ path('getMovieDetail', {'imdbID': result.imdbID}) }}">
                                            <img src="{{ result.Poster }}" alt="poster" class='poster'>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('getMovieDetail', {'imdbID': result.imdbID}) }}">
                                            {{ result.Title }} <br> {{ result.Year }} 
                                        </a>
                                    </td>
                                    <td>{{ result.Type }}</td>
                                    <td>
                                        <label class="container">
                                            <input 
                                                type="checkbox" 
                                                name='movies[{{ result.imdbID }}][to_see]'
                                                {{ to_see }}
                                            >
                                            <span class="checkmark"></span>
                                        </label>
                                    </td>
                                    <td>
                                        <label class="container">
                                            <input 
                                                type="checkbox" 
                                                name='movies[{{ result.imdbID }}][see]' 
                                                {{ see }}
                                            >
                                            <span class="checkmark"></span>
                                        </label>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class='bottom-form'>
                        <a 
                            href="{{ path('searchMoviePage', {'page': page - 1, 'search': search}) }}" 
                            class="rkmd-btn btn-lightBlue ripple-effect"
                        >
                            Précédent
                        </a>

                        <input type="submit" value="Enregister" class="rkmd-btn btn-green ripple-effect"> 

                        <a 
                            href="{{ path('searchMoviePage', {'page': page + 1, 'search': search}) }}"
                            class="rkmd-btn btn-lightBlue ripple-effect"
                        >
                            Suivant
                        </a>
                    </div>
                </form>
            {% endif %}

        {% if error is defined and error|length > 0 %}
            <div class='error'>
                <span>
                    {{ error }}
                </span>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}